#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QuanLyTDP")]
	public partial class dataDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertDongGopPhi(DongGopPhi instance);
    partial void UpdateDongGopPhi(DongGopPhi instance);
    partial void DeleteDongGopPhi(DongGopPhi instance);
    partial void InsertPhiVeSinh(PhiVeSinh instance);
    partial void UpdatePhiVeSinh(PhiVeSinh instance);
    partial void DeletePhiVeSinh(PhiVeSinh instance);
    partial void InsertHocGiaDinh(HocGiaDinh instance);
    partial void UpdateHocGiaDinh(HocGiaDinh instance);
    partial void DeleteHocGiaDinh(HocGiaDinh instance);
    partial void InsertNguoiCuTru(NguoiCuTru instance);
    partial void UpdateNguoiCuTru(NguoiCuTru instance);
    partial void DeleteNguoiCuTru(NguoiCuTru instance);
    #endregion
		
		public dataDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dataDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dataDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
        public dataDataContext() :
         base(global::System.Configuration.ConfigurationManager.ConnectionStrings["QuanLyTDPConnectionString1"].ConnectionString, mappingSource)
        {
            OnCreated();
        }
        public dataDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<DongGopPhi> DongGopPhis
		{
			get
			{
				return this.GetTable<DongGopPhi>();
			}
		}
		
		public System.Data.Linq.Table<PhiVeSinh> PhiVeSinhs
		{
			get
			{
				return this.GetTable<PhiVeSinh>();
			}
		}
		
		public System.Data.Linq.Table<HocGiaDinh> HocGiaDinhs
		{
			get
			{
				return this.GetTable<HocGiaDinh>();
			}
		}
		
		public System.Data.Linq.Table<NguoiCuTru> NguoiCuTrus
		{
			get
			{
				return this.GetTable<NguoiCuTru>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DongGopPhi")]
	public partial class DongGopPhi : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaDongGop;
		
		private System.Nullable<int> _MaHocGiaDinh;
		
		private string _LoaiDongGop;
		
		private System.Nullable<decimal> _SoTien;
		
		private System.Nullable<System.DateTime> _NgayDongGop;
		
		private EntityRef<HocGiaDinh> _HocGiaDinh;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaDongGopChanging(int value);
    partial void OnMaDongGopChanged();
    partial void OnMaHocGiaDinhChanging(System.Nullable<int> value);
    partial void OnMaHocGiaDinhChanged();
    partial void OnLoaiDongGopChanging(string value);
    partial void OnLoaiDongGopChanged();
    partial void OnSoTienChanging(System.Nullable<decimal> value);
    partial void OnSoTienChanged();
    partial void OnNgayDongGopChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayDongGopChanged();
    #endregion
		
		public DongGopPhi()
		{
			this._HocGiaDinh = default(EntityRef<HocGiaDinh>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDongGop", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaDongGop
		{
			get
			{
				return this._MaDongGop;
			}
			set
			{
				if ((this._MaDongGop != value))
				{
					this.OnMaDongGopChanging(value);
					this.SendPropertyChanging();
					this._MaDongGop = value;
					this.SendPropertyChanged("MaDongGop");
					this.OnMaDongGopChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHocGiaDinh", DbType="Int")]
		public System.Nullable<int> MaHocGiaDinh
		{
			get
			{
				return this._MaHocGiaDinh;
			}
			set
			{
				if ((this._MaHocGiaDinh != value))
				{
					if (this._HocGiaDinh.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaHocGiaDinhChanging(value);
					this.SendPropertyChanging();
					this._MaHocGiaDinh = value;
					this.SendPropertyChanged("MaHocGiaDinh");
					this.OnMaHocGiaDinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoaiDongGop", DbType="NVarChar(100)")]
		public string LoaiDongGop
		{
			get
			{
				return this._LoaiDongGop;
			}
			set
			{
				if ((this._LoaiDongGop != value))
				{
					this.OnLoaiDongGopChanging(value);
					this.SendPropertyChanging();
					this._LoaiDongGop = value;
					this.SendPropertyChanged("LoaiDongGop");
					this.OnLoaiDongGopChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoTien", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> SoTien
		{
			get
			{
				return this._SoTien;
			}
			set
			{
				if ((this._SoTien != value))
				{
					this.OnSoTienChanging(value);
					this.SendPropertyChanging();
					this._SoTien = value;
					this.SendPropertyChanged("SoTien");
					this.OnSoTienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayDongGop", DbType="Date")]
		public System.Nullable<System.DateTime> NgayDongGop
		{
			get
			{
				return this._NgayDongGop;
			}
			set
			{
				if ((this._NgayDongGop != value))
				{
					this.OnNgayDongGopChanging(value);
					this.SendPropertyChanging();
					this._NgayDongGop = value;
					this.SendPropertyChanged("NgayDongGop");
					this.OnNgayDongGopChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HocGiaDinh_DongGopPhi", Storage="_HocGiaDinh", ThisKey="MaHocGiaDinh", OtherKey="MaHocGiaDinh", IsForeignKey=true)]
		public HocGiaDinh HocGiaDinh
		{
			get
			{
				return this._HocGiaDinh.Entity;
			}
			set
			{
				HocGiaDinh previousValue = this._HocGiaDinh.Entity;
				if (((previousValue != value) 
							|| (this._HocGiaDinh.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HocGiaDinh.Entity = null;
						previousValue.DongGopPhis.Remove(this);
					}
					this._HocGiaDinh.Entity = value;
					if ((value != null))
					{
						value.DongGopPhis.Add(this);
						this._MaHocGiaDinh = value.MaHocGiaDinh;
					}
					else
					{
						this._MaHocGiaDinh = default(Nullable<int>);
					}
					this.SendPropertyChanged("HocGiaDinh");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PhiVeSinh")]
	public partial class PhiVeSinh : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaPhi;
		
		private System.Nullable<int> _MaHocGiaDinh;
		
		private System.Nullable<decimal> _SoTien;
		
		private System.Nullable<int> _Thang;
		
		private System.Nullable<int> _Nam;
		
		private EntityRef<HocGiaDinh> _HocGiaDinh;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaPhiChanging(int value);
    partial void OnMaPhiChanged();
    partial void OnMaHocGiaDinhChanging(System.Nullable<int> value);
    partial void OnMaHocGiaDinhChanged();
    partial void OnSoTienChanging(System.Nullable<decimal> value);
    partial void OnSoTienChanged();
    partial void OnThangChanging(System.Nullable<int> value);
    partial void OnThangChanged();
    partial void OnNamChanging(System.Nullable<int> value);
    partial void OnNamChanged();
    #endregion
		
		public PhiVeSinh()
		{
			this._HocGiaDinh = default(EntityRef<HocGiaDinh>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaPhi", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaPhi
		{
			get
			{
				return this._MaPhi;
			}
			set
			{
				if ((this._MaPhi != value))
				{
					this.OnMaPhiChanging(value);
					this.SendPropertyChanging();
					this._MaPhi = value;
					this.SendPropertyChanged("MaPhi");
					this.OnMaPhiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHocGiaDinh", DbType="Int")]
		public System.Nullable<int> MaHocGiaDinh
		{
			get
			{
				return this._MaHocGiaDinh;
			}
			set
			{
				if ((this._MaHocGiaDinh != value))
				{
					if (this._HocGiaDinh.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaHocGiaDinhChanging(value);
					this.SendPropertyChanging();
					this._MaHocGiaDinh = value;
					this.SendPropertyChanged("MaHocGiaDinh");
					this.OnMaHocGiaDinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoTien", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> SoTien
		{
			get
			{
				return this._SoTien;
			}
			set
			{
				if ((this._SoTien != value))
				{
					this.OnSoTienChanging(value);
					this.SendPropertyChanging();
					this._SoTien = value;
					this.SendPropertyChanged("SoTien");
					this.OnSoTienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Thang", DbType="Int")]
		public System.Nullable<int> Thang
		{
			get
			{
				return this._Thang;
			}
			set
			{
				if ((this._Thang != value))
				{
					this.OnThangChanging(value);
					this.SendPropertyChanging();
					this._Thang = value;
					this.SendPropertyChanged("Thang");
					this.OnThangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nam", DbType="Int")]
		public System.Nullable<int> Nam
		{
			get
			{
				return this._Nam;
			}
			set
			{
				if ((this._Nam != value))
				{
					this.OnNamChanging(value);
					this.SendPropertyChanging();
					this._Nam = value;
					this.SendPropertyChanged("Nam");
					this.OnNamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HocGiaDinh_PhiVeSinh", Storage="_HocGiaDinh", ThisKey="MaHocGiaDinh", OtherKey="MaHocGiaDinh", IsForeignKey=true)]
		public HocGiaDinh HocGiaDinh
		{
			get
			{
				return this._HocGiaDinh.Entity;
			}
			set
			{
				HocGiaDinh previousValue = this._HocGiaDinh.Entity;
				if (((previousValue != value) 
							|| (this._HocGiaDinh.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HocGiaDinh.Entity = null;
						previousValue.PhiVeSinhs.Remove(this);
					}
					this._HocGiaDinh.Entity = value;
					if ((value != null))
					{
						value.PhiVeSinhs.Add(this);
						this._MaHocGiaDinh = value.MaHocGiaDinh;
					}
					else
					{
						this._MaHocGiaDinh = default(Nullable<int>);
					}
					this.SendPropertyChanged("HocGiaDinh");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HocGiaDinh")]
	public partial class HocGiaDinh : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaHocGiaDinh;
		
		private string _DiaChi;
		
		private System.Nullable<int> _TongSoNguoiTrongGiaDinh;
		
		private string _ThongTinLienHe;
		
		private EntitySet<DongGopPhi> _DongGopPhis;
		
		private EntitySet<PhiVeSinh> _PhiVeSinhs;
		
		private EntitySet<NguoiCuTru> _NguoiCuTrus;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaHocGiaDinhChanging(int value);
    partial void OnMaHocGiaDinhChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnTongSoNguoiTrongGiaDinhChanging(System.Nullable<int> value);
    partial void OnTongSoNguoiTrongGiaDinhChanged();
    partial void OnThongTinLienHeChanging(string value);
    partial void OnThongTinLienHeChanged();
    #endregion
		
		public HocGiaDinh()
		{
			this._DongGopPhis = new EntitySet<DongGopPhi>(new Action<DongGopPhi>(this.attach_DongGopPhis), new Action<DongGopPhi>(this.detach_DongGopPhis));
			this._PhiVeSinhs = new EntitySet<PhiVeSinh>(new Action<PhiVeSinh>(this.attach_PhiVeSinhs), new Action<PhiVeSinh>(this.detach_PhiVeSinhs));
			this._NguoiCuTrus = new EntitySet<NguoiCuTru>(new Action<NguoiCuTru>(this.attach_NguoiCuTrus), new Action<NguoiCuTru>(this.detach_NguoiCuTrus));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHocGiaDinh", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaHocGiaDinh
		{
			get
			{
				return this._MaHocGiaDinh;
			}
			set
			{
				if ((this._MaHocGiaDinh != value))
				{
					this.OnMaHocGiaDinhChanging(value);
					this.SendPropertyChanging();
					this._MaHocGiaDinh = value;
					this.SendPropertyChanged("MaHocGiaDinh");
					this.OnMaHocGiaDinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(255)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TongSoNguoiTrongGiaDinh", DbType="Int")]
		public System.Nullable<int> TongSoNguoiTrongGiaDinh
		{
			get
			{
				return this._TongSoNguoiTrongGiaDinh;
			}
			set
			{
				if ((this._TongSoNguoiTrongGiaDinh != value))
				{
					this.OnTongSoNguoiTrongGiaDinhChanging(value);
					this.SendPropertyChanging();
					this._TongSoNguoiTrongGiaDinh = value;
					this.SendPropertyChanged("TongSoNguoiTrongGiaDinh");
					this.OnTongSoNguoiTrongGiaDinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThongTinLienHe", DbType="NVarChar(255)")]
		public string ThongTinLienHe
		{
			get
			{
				return this._ThongTinLienHe;
			}
			set
			{
				if ((this._ThongTinLienHe != value))
				{
					this.OnThongTinLienHeChanging(value);
					this.SendPropertyChanging();
					this._ThongTinLienHe = value;
					this.SendPropertyChanged("ThongTinLienHe");
					this.OnThongTinLienHeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HocGiaDinh_DongGopPhi", Storage="_DongGopPhis", ThisKey="MaHocGiaDinh", OtherKey="MaHocGiaDinh")]
		public EntitySet<DongGopPhi> DongGopPhis
		{
			get
			{
				return this._DongGopPhis;
			}
			set
			{
				this._DongGopPhis.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HocGiaDinh_PhiVeSinh", Storage="_PhiVeSinhs", ThisKey="MaHocGiaDinh", OtherKey="MaHocGiaDinh")]
		public EntitySet<PhiVeSinh> PhiVeSinhs
		{
			get
			{
				return this._PhiVeSinhs;
			}
			set
			{
				this._PhiVeSinhs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HocGiaDinh_NguoiCuTru", Storage="_NguoiCuTrus", ThisKey="MaHocGiaDinh", OtherKey="MaHocGiaDinh")]
		public EntitySet<NguoiCuTru> NguoiCuTrus
		{
			get
			{
				return this._NguoiCuTrus;
			}
			set
			{
				this._NguoiCuTrus.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DongGopPhis(DongGopPhi entity)
		{
			this.SendPropertyChanging();
			entity.HocGiaDinh = this;
		}
		
		private void detach_DongGopPhis(DongGopPhi entity)
		{
			this.SendPropertyChanging();
			entity.HocGiaDinh = null;
		}
		
		private void attach_PhiVeSinhs(PhiVeSinh entity)
		{
			this.SendPropertyChanging();
			entity.HocGiaDinh = this;
		}
		
		private void detach_PhiVeSinhs(PhiVeSinh entity)
		{
			this.SendPropertyChanging();
			entity.HocGiaDinh = null;
		}
		
		private void attach_NguoiCuTrus(NguoiCuTru entity)
		{
			this.SendPropertyChanging();
			entity.HocGiaDinh = this;
		}
		
		private void detach_NguoiCuTrus(NguoiCuTru entity)
		{
			this.SendPropertyChanging();
			entity.HocGiaDinh = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NguoiCuTru")]
	public partial class NguoiCuTru : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaNguoiCuTru;
		
		private System.Nullable<int> _MaHocGiaDinh;
		
		private string _HoTen;
		
		private System.Nullable<int> _Tuoi;
		
		private string _GioiTinh;
		
		private string _MoiQuanHe;
		
		private EntityRef<HocGiaDinh> _HocGiaDinh;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNguoiCuTruChanging(int value);
    partial void OnMaNguoiCuTruChanged();
    partial void OnMaHocGiaDinhChanging(System.Nullable<int> value);
    partial void OnMaHocGiaDinhChanged();
    partial void OnHoTenChanging(string value);
    partial void OnHoTenChanged();
    partial void OnTuoiChanging(System.Nullable<int> value);
    partial void OnTuoiChanged();
    partial void OnGioiTinhChanging(string value);
    partial void OnGioiTinhChanged();
    partial void OnMoiQuanHeChanging(string value);
    partial void OnMoiQuanHeChanged();
    #endregion
		
		public NguoiCuTru()
		{
			this._HocGiaDinh = default(EntityRef<HocGiaDinh>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNguoiCuTru", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaNguoiCuTru
		{
			get
			{
				return this._MaNguoiCuTru;
			}
			set
			{
				if ((this._MaNguoiCuTru != value))
				{
					this.OnMaNguoiCuTruChanging(value);
					this.SendPropertyChanging();
					this._MaNguoiCuTru = value;
					this.SendPropertyChanged("MaNguoiCuTru");
					this.OnMaNguoiCuTruChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHocGiaDinh", DbType="Int")]
		public System.Nullable<int> MaHocGiaDinh
		{
			get
			{
				return this._MaHocGiaDinh;
			}
			set
			{
				if ((this._MaHocGiaDinh != value))
				{
					if (this._HocGiaDinh.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaHocGiaDinhChanging(value);
					this.SendPropertyChanging();
					this._MaHocGiaDinh = value;
					this.SendPropertyChanged("MaHocGiaDinh");
					this.OnMaHocGiaDinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NVarChar(100)")]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this.OnHoTenChanging(value);
					this.SendPropertyChanging();
					this._HoTen = value;
					this.SendPropertyChanged("HoTen");
					this.OnHoTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tuoi", DbType="Int")]
		public System.Nullable<int> Tuoi
		{
			get
			{
				return this._Tuoi;
			}
			set
			{
				if ((this._Tuoi != value))
				{
					this.OnTuoiChanging(value);
					this.SendPropertyChanging();
					this._Tuoi = value;
					this.SendPropertyChanged("Tuoi");
					this.OnTuoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiTinh", DbType="NVarChar(10)")]
		public string GioiTinh
		{
			get
			{
				return this._GioiTinh;
			}
			set
			{
				if ((this._GioiTinh != value))
				{
					this.OnGioiTinhChanging(value);
					this.SendPropertyChanging();
					this._GioiTinh = value;
					this.SendPropertyChanged("GioiTinh");
					this.OnGioiTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MoiQuanHe", DbType="NVarChar(50)")]
		public string MoiQuanHe
		{
			get
			{
				return this._MoiQuanHe;
			}
			set
			{
				if ((this._MoiQuanHe != value))
				{
					this.OnMoiQuanHeChanging(value);
					this.SendPropertyChanging();
					this._MoiQuanHe = value;
					this.SendPropertyChanged("MoiQuanHe");
					this.OnMoiQuanHeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HocGiaDinh_NguoiCuTru", Storage="_HocGiaDinh", ThisKey="MaHocGiaDinh", OtherKey="MaHocGiaDinh", IsForeignKey=true)]
		public HocGiaDinh HocGiaDinh
		{
			get
			{
				return this._HocGiaDinh.Entity;
			}
			set
			{
				HocGiaDinh previousValue = this._HocGiaDinh.Entity;
				if (((previousValue != value) 
							|| (this._HocGiaDinh.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HocGiaDinh.Entity = null;
						previousValue.NguoiCuTrus.Remove(this);
					}
					this._HocGiaDinh.Entity = value;
					if ((value != null))
					{
						value.NguoiCuTrus.Add(this);
						this._MaHocGiaDinh = value.MaHocGiaDinh;
					}
					else
					{
						this._MaHocGiaDinh = default(Nullable<int>);
					}
					this.SendPropertyChanged("HocGiaDinh");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
